name: async_var
description: "Async Data, Loading notifier, Error all in one variable, reducing boilerplate code and making your code more concise"
version: 1.1.4
repository: https://github.com/flexxxlab/async_var
homepage: https://us.flexxxlab.com/
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
  
environment:
  sdk: ^3.10.3
  flutter: ">=2.51.1"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true